name: CI Pipeline
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Action
      - uses: actions/checkout@v3

      # Step (run command)
      - name: Install dependencies
        run: npm install

      # Step (using an action)
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step (run tests)
      - name: Run tests
        run: npm test
